<template>
    <div id="content">
        <page-header title="Politika" />
        <p>Vždycky jsem dění u&nbsp;nás a&nbsp;ve světě sledoval, ale dlouho by mě nenapadlo dělat něco víc. Instinktivně jsem tíhl k&nbsp;politické pravici a&nbsp;k&nbsp;zásadě, ať se každý snaží o&nbsp;své životní štěstí sám a&nbsp;stát ať dá pokoj jemu i&nbsp;ostatním. Díky tomu jsem si našel <a href="https://www.svobodni.cz/">Svobodné</a>. Po čase mi začalo dávat smysl, abych místo <em>"oni Svobodní"</em> mohl říkat <em>"my Svobodní"</em>. A&nbsp;tak jsem se právě v&nbsp;den, kdy jsem úspěšně složil závěrečnou baklářskou zkoušku na VŠE koncem června 2013, rozhodl podat přihlášku.</p>
        <a href="https://www.svobodni.cz/"><img src="/logo/svobodni.webp" class="activities logo" alt="svobodni.cz"></a>
        <p>Nevěděl jsem, co od toho čekat, ale vlétl jsem do dění po hlavě. Pomáhal jsem v&nbsp;parlamentní kampani 2013, a&nbsp;pak mě nenapadlo nic lepšího, než využít práva člena kandidovat na místopředsedu strany. Neuspěl jsem, ale leccos si přitom vyzkoušel a&nbsp;hlavně mě na základě mé aktivity oslovil tehdejší předseda Pražské organizace Jiří Kubíček, jestli bych se nechtěl ujmout pobočky v&nbsp;Praze&nbsp;4 před komunálními volbami 2014? Tak začala koncem roku 2013 má politická aktivita. Začal jsem chodit na jednání našeho zastupitelstva, seznamoval se z&nbsp;lidmi a&nbsp;snažil se se Svobodnými uspět. Také jsem dostal a&nbsp;přijal nabídku pomáhat s&nbsp;chodem strany na centrální úrovni, což po nečekaném úspěchu Petra Macha v&nbsp;EP volbách na jaře 2014 vyústilo na rok a&nbsp;půl i&nbsp;v&nbsp;práci lokálního asistenta nového Europoslance. Jako aktivní člen jsem snadno získal pozici v&nbsp;našem Republikovém výboru a&nbsp;v&nbsp;roce 2017 jsem byl zvolen jedním ze čtyř místopředsedů. Pozici jsem o&nbsp;dva roky později obhájil a&nbsp;rád bych pokračoval i&nbsp;nadále.</p>
        <p>Do zastupitelstva Prahy 4 v&nbsp;letech 2014 ani 2018 to nakonec nikomu ze Svobodných nevyšlo. Při prvním pokusu těsně, při druhém o&nbsp;dost. Ani v&nbsp;jiných volbách se nám až tak moc nedařilo. Myšlenka <em>"stát by měl dělat méně"</em> není příliš populární, udělali jsme dost chyb a&nbsp;vedli zbytečné debaty a&nbsp;hádky místo užitečné práce. Občas si říkám, jestli to má vůbec cenu? Ale když už jsem si jednou řekl, že mi to stojí za to, tak se nehodlám jen tak vzdát. Poznal jsem díky pokusům o&nbsp;účast v&nbsp;politice desítky inspirativních lidí,&nbsp;leccos zajímavého zažil a&nbsp;dokonce byl v&nbsp;Politickém spektru v&nbsp;televizi. Takže jedeme dál.</p>
        <p>Komentáře k&nbsp;politice asi nejčastěji píšu přímo na <a href="https://www.facebook.com/alois.seckar">Facebooku</a>, někdy se mi povede zveřejnit delší text na blogu <a href="https://seckar.blog.idnes.cz/">https://seckar.blog.idnes.cz/</a>.</p>
        <page-footer />
    </div>
</template>

<script>
    import "@/assets/css/as.css";
</script>