<template>
    <div id="content">
        <page-header title="Sport" />
        <p>Vzorem sportovce jsem nikdy úplně nebyl, ale i&nbsp;přes nadváhu a&nbsp;nešikovnost jsem se po letech tápání a&nbsp;pokusů (taekwon-do, florbal, veslování) v&nbsp;několika sportech nakonec našel.</p>
        <h2>Běhání</h2>
        <p>S&nbsp;pravidelným běháním jsem začal na jaře 2013. Nebylo to úplně dobrovolné rozhodnutí, nýbrž určitá reakce na zdravotní problémy. Docela to však pomohlo, zhubnul jsem, zesílil a&nbsp;hlavně si našel skutečnou zálibu. Neberu to už jako nepříjemnou povinnost, ale jako zábavu, a&nbsp;chybí mi, pokud z&nbsp;nějakého důvodu delší dobu běhat nemůžu. V&nbsp;současnosti běžně uběhnu kolem 100-120&nbsp;km za měsíc. Když si dobře vyberu závod, tak se občas i&nbsp;umístím někde v&nbsp;popředí, i&nbsp;když lehce stavěným "skutečným" atletům se svou hřmotnou postavou reálně konkurovat nemůžu.</p>
        <p>Na první maraton jsem si troufl v&nbsp;květnu 2017, celkem jsem jich dokončil šest. Ale můj nejtěžší dosavadní závod byl Sky Race Černá Hora v&nbsp;Krkonoších v&nbsp;září 2019 - 30&nbsp;km a&nbsp;2&nbsp;km převýšení. A&nbsp;můj největší běžecký zážitek byl štafetový půlmaraton v&nbsp;týmu s&nbsp;olympionikem Davidem Svobodou.</p>
        <a href="/beh.webp"><img src="/beh.webp" class="activities photo" alt="Craft Team Running 2018"></a>
        <p>Od 1.&nbsp;ledna 2019 jsem jako vedoucí <em>Oddílu rekreačního běhu</em> členem <a href="http://www.tjsokolprahakrc.cz/">Sokola Krč</a>. Spolu s&nbsp;tátou se snažíme pomáhat držet tradici (v&nbsp;Krči od roku 1893) a&nbsp;pořádat akce a&nbsp;závody. Našim zatím největším počinem byla <a href="http://tgmstafeta2020.cz/">TGM štafeta</a> v&nbsp;březnu 2020, kdy jsme s&nbsp;týmem nadšených běžců běželi štafetově 360&nbsp;km z&nbsp;Hodonína do Lán u&nbsp;příležitosti výročí narození prezidenta Masaryka. V&nbsp;zájmu činnosti oddílu jsem také na jaře 2019 absolvoval víkendový kurz <em>Trenéra kondičního běhu 3.&nbsp;třídy</em>. Musím ovšem říct, že této oblasti zatím nezvládám dávat tolik, kolik by potřebovala.</p>
        <a href="http://www.tjsokolprahakrc.cz/"><img src="/logo/sokol-krc.webp" class="activities logo" alt="TJ Sokol Praha-Krč"></a>
        <p>Od konce roku 2020 používám aplikaci Strava, ale hlavně si už od prvního výběhu v&nbsp;březnu 2013 všechny výkony poctivě zaznamenávám na jednoduchém webu <a href="http://ellrohir.mzf.cz/run.php">http://ellrohir.mzf.cz/run.php</a>, kde se na ně můžete podívat i&nbsp;vy.</p>
        <p>Moje nejlepší výkony:</p>
        <ul>
            <li>1km -&nbsp;3:37</li>
            <li>5km -&nbsp;21:39</li>
            <li>10km -&nbsp;45:08</li>
            <li>21km -&nbsp;1:49:09</li>
            <li>42km -&nbsp;3:42:29</li>
        </ul>
        <h2>Softball a&nbsp;baseball</h2>
        <p>Sofball jsme prvně hráli na gymnáziu, kde mě to zaujalo natolik, že jsem si ho potom na vysoké škole vybral jako volitelný sport. Tam přišla nabídka začít hrát "doopravdy", a&nbsp;tak jsem na začátku roku 2008 přišel do týmu <strong>MFF Neratovice</strong>, kde jsem odehrál několik pěkných sezón v&nbsp;2.&nbsp;lize doplňovaných o&nbsp;zápasy B-týmu v&nbsp;Pražském přeboru. Když se spoluhráči po jedné ze sezón rozhodli 2.&nbsp;ligu dobrovolně opustit, přesunul jsem se do týmu <strong>Mistrál Praha</strong>, který sice ligu rovněž nehrál, ale vypadal tehdy, že má ambice jít brzy výš. Nakonec to dopadlo trochu jinak -&nbsp;po rozkolu uvnitř týmu se odštěpili "mladí a nadějní". Já zůstal loajální trenérovi, ale Mistrál pak moc dlouho nevydržel a&nbsp;pro nedostatek hráčů a&nbsp;vůle táhnout to dál necelé dva roky na to skončil. Já pak na dlouho víceméně přestal hrát -&nbsp;jen chvíli pár zápasů v&nbsp;1.&nbsp;třídě za <strong>Bohemians Praha</strong> -&nbsp;a&nbsp;už jsem měl tak nějak za to, že má kariéra aktivního softbalisty skončila. V&nbsp;červenci 2021 se mi ovšem ozval Petr Ševčík z&nbsp;<strong>Pikes Praha</strong> (oni "mladí a nadějní" z&nbsp;někdejšího Mistrálu), jestli bych jim náhodou nepřijel pomoct do Ledenic na zápasy 2.&nbsp;ligy. A&nbsp;tak přišel nečekaný restart a můžu&nbsp;napsat, že už znovu aktivně hraju.</p>
        <a href="https://www.pikes.cz/"><img src="/logo/pikes.webp" class="activities logo" alt="Pikes Praha"></a>
        <p>Paralelně s&nbsp;tím se od počátku věnuju činosti zapisovatele. Dění na hřišti je potřeba zapsat, aby pak bylo možné zpracovat statistiky. Dělá se to jak ručně na papír, tak poslední dobou čím dál víc elektronicky vč. textového online přenosu. V&nbsp;roce 2009 jsem se přihlásil jako dobrovolník na první mezinárodní turnaj, a&nbsp;tak začala má cesta mezi ty nejlepší zapisovatele v&nbsp;ČR a&nbsp;pevně doufám, že i&nbsp;mezi nejlepší v&nbsp;Evropě a&nbsp;jednou snad i&nbsp;na světě. Pravidelně každé léto zapisuju několik soutěží pod hlavičkou evropských federací ESF a CEB (v posledné době slučovaných pod jednotnou WBSC), podíval jsem se už i&nbsp;do zahraničí. Začínal jsem prvně jen u&nbsp;softbalových turnajů, v&nbsp;roce 2012 mě vzali jako výpomoc na první baseballový turnaj (U15 v&nbsp;Jablonci a&nbsp;Liberci) a&nbsp;od té doby kombinuju obojí. V&nbsp;baseballu jsem jako hlavní zapisovatel vedl např. ME&nbsp;hráčů do 23&nbsp;let v&nbsp;roce 2017. V&nbsp;tomtéž roce mi dali také cenu <em>"CEB zapisovatel roku"</em>. V&nbsp;softballu jsem vedl celou řadu ME a&nbsp;dostal příležitost i&nbsp;na MS mužů hraném v&nbsp;roce 2019 v&nbsp;Praze. V&nbsp;červnu téhož roku jsem byl nominován na mezinárodní školení zapisovatelů WBSC do San José v&nbsp;Kalifornii. Na domácí scéně jsem přededou Komise zapisovatelů ČBA a&nbsp;členem Komise zapsiovatelů ČSA. Staráme se o&nbsp;organizaci zápisu v&nbsp;českých ligových soutěžích a&nbsp;přes zimu školíme nové zapisovatele. Mým snem je zúčastnit se jednou jako zapisovatel Olympijských her.</p>
        <p>Další rolí, kterou jsem si vyzkoušel, je rozhodčí. Častěji v&nbsp;softballu, ale certifikaci a&nbsp;zkušenosti mám opět v&nbsp;obou pálkovacích sportech. Jednu chvíli jsem se tomu věnoval docela intenzivně a&nbsp;celkem mi to šlo. Mám na kontě i&nbsp;několik zápasů v&nbsp;ženské i&nbsp;mužské softballové extralize a&nbsp;jeden výlet na nejvyšší dámskou soutěž do Rakouska. S&nbsp;nástupem do zaměstnání však ubylo volného času a&nbsp;(celkem slušná) finanční odměna přestala být takovou motivací. Navíc jsou to občas nervy a&nbsp;stres, což jsem usoudil, že nemám tak úplně zapotřebí. V&nbsp;případě potřeby občas někde vypomůžu, ale jednoznačně dávám přednost zapisování.</p>
        <h2>Malý fotbal</h2>
        <p>S několika spolužáky z&nbsp;gymnázia jsme někdy kolem roku 2008 začali hrát Hanspaulskou ligu <a href="http://www.psmf.cz">PSMF</a> a&nbsp;od té doby se nás to drží. Náš tým jménem <strong>Kopanda FC</strong> se postupně obměňuje a&nbsp;doplňuje, jádro zatím stále zůstává. Hrajeme teď 7.&nbsp;ligu (z&nbsp;osmi), někdy to jde líp a&nbsp;jindy hůř. Já na fotbal obecně nejsem moc šikovný, ale našel jsem si už dávno své místo v&nbsp;bráně a&nbsp;snažím se to tam moc nekazit.</p>
        <a href="/kopanda.webp"><img src="/kopanda.webp" class="activities photo" alt="Kopanda FC"></a>
        <page-footer />
    </div>
</template>

<script>
    import "@/assets/css/as.css";
</script>